### ISSUE TITLE
Booting Error

### ISSUE THREAD

**Issue by Blurayx** [SpiralLinux/SpiralLinux-project#150]
Hi,
Getting an error when trying to boot into the live USB.
I’ve tried etcher and Rufus, resulting in the same boot errors.

Thanks

**Comment by geckolinux** [comment]
Hi there, we would definitely need a lot more information in order to help.

**Comment by Blurayx** [comment]
I'm so sorry, I meant to attach a photo
![IMG_0074](https://user-images.githubusercontent.com/2873112/194948668-70ecd546-806b-4576-b576-b012e7d33401.JPG)

**Comment by geckolinux** [comment]
Hi there, could you please try disabling SecureBoot?

**Comment by Blurayx** [comment]
Hi,
SecureBoot is disabled. 

Thanks

**Comment by CicadaSeventeen** [comment]
Could you try using Fedora media writer rather than Rufus? 
Fedora media writer is available from flathub. Also Windows and Macos versions from Fedora official site.

**Comment by Blurayx** [comment]
Unfortunately, the fedora media writer didn't work. I think we're out of options.

Thanks for all your help 🙂

**Comment by bliu13** [comment]
@Blurayx, I had good results using etcher [mentioned in the wiki](https://github.com/SpiralLinux/SpiralLinux-project/wiki#how-to-create-a-bootable-spirallinux-usb-stick). You definitely can have Secure Boot enabled.

**Comment by Blurayx** [comment]
According to Asus, when PK is set to "0" Secure Boot is disabled .

![SB](https://user-images.githubusercontent.com/2873112/195682485-9fb55b2d-efd0-4617-a7b3-34e71d804e81.JPG)

**Comment by geckolinux** [comment]
Hi @Blurayx , sorry for the slow reply. While SpiralLinux does support SecureBoot, I still recommend disabling it because I dislike the additional complication and errors due to buggy EFI implementations like what you're seeing.

This is what I can find from Asus about disabling SecureBoot:
https://www.asus.com/support/FAQ/1042711
![2ffaf8b9-132b-4e04-aa27-6e625392d49e](https://user-images.githubusercontent.com/2692138/196037911-0e73de02-48d0-4a2e-9044-d992541ffb05.png)

Also you might have to look for an option to delete and/or reset all SecureBoot keys, and you might have to change the bootloader priority too. Note that this might cause problems with booting other operating systems that you might currently have installed on that machine.

I have seen that error before on some laptops of mine, and I know it can be fixed, but it depends on a lot of unique circumstances of the machine. Please let us know first how it goes by trying to fully disable SecureBoot and delete/reset all the keys.
