### ISSUE TITLE
Remove `sources-media` from Calamares settings.conf

### ISSUE THREAD

**Issue by geckolinux** [SpiralLinux/SpiralLinux-project#201]
To eliminate random hangs.

**Comment by MarkHaw** [comment]
Ran into this problem last night while trying to reinstall the Sept versions of XFCE alongside windows 10 on an older Lenovo mini. The installation timed out at 38% when it tried to execute sources-media. I tried multiple times with both the XFCE and Mate versions with the same results. I needed to do this install because I reinstalled Windows due to update problems (oh too common). The first time I installed the Sept version alongside windows in Sept, everything worked fine.

**Comment by MarkHaw** [comment]
Thanks, I'll give it a try.

**Comment by geckolinux** [comment]
Implemented in https://github.com/SpiralLinux/SpiralLinux-project/releases/tag/12.231001
