### ISSUE TITLE
Migrate GNOME default config overrides into simple system-wide configs

### ISSUE THREAD

**Issue by xalt7x** [SpiralLinux/SpiralLinux-project#293]
Currently GNOME edition stores dconf database in
/etc/skel/.config/dconf/user
file which eventually copies into
$HOME/.config/dconf/user

Database content can't be opened with a simple text editor.
User [needs to dump it](https://unix.stackexchange.com/questions/199836/how-can-i-view-the-content-of-a-backup-of-the-dconf-database-file) first.
GNOME 3.x provides a better mechanism for administrators.
One can customize [GDM/login settings](https://help.gnome.org/admin/system-admin-guide/stable/login.html.en) and [session/user settings](https://help.gnome.org/admin/system-admin-guide/stable/user-settings.html.en).

Files are easily readable, override default settings and survive system upgrades better.

---

Examples:

1. Enable "tap-to-click" touchpad setting on GDM login screen

/etc/dconf/profile/gdm
```
user-db:user
system-db:gdm
file-db:/usr/share/gdm/greeter-dconf-defaults
```
/etc/dconf/db/gdm.d/01-custom
```
[org/gnome/desktop/peripherals/touchpad]
tap-to-click=true
```

---

2. Enable "tap-to-click" touchpad setting for a user session

/etc/dconf/profile/user
```
user-db:user
system-db:local
```
/etc/dconf/db/local.d/01-custom
```
[org/gnome/desktop/peripherals/touchpad]
tap-to-click=true
```

**Comment by geckolinux** [comment]
Thanks for the excellent suggestion. Due to the very large number of customizations to dconf across all the different SpiralLinux editions it's not really practical to implement all the overrides in this way. Basically to create the configuration I load up the SpiralLinux system in a VM and configure the desktop visually and then copy the `~/.config/dconf/user` file to the ISO live build `/etc/skel/` directory. However there are a few settings that aren't practical to implement that way, and I have set them as you suggest in https://github.com/SpiralLinux/SpiralLinux-project/releases/tag/12.231001
