### ISSUE TITLE
btrfs-assistant

### ISSUE THREAD

**Issue by danboid** [SpiralLinux/SpiralLinux-project#407]
I know its already easy to rollback using the snapper-rollback command but some people prefer to do most or all things using the GUI whereever possible so it would be good if SpiralLinux installed btrfs-assistant by default, or at least when the user installs using btrfs. 

https://gitlab.com/btrfs-assistant/btrfs-assistant

I don't think snapper-gui supports doing rollbacks does it?

**Comment by geckolinux** [comment]
Hi there, thanks for the suggestion. I agree that btrfs-assistant might be a useful tool for those who want to install it, but I'm reluctant to ship by default in SpiralLinux anything more complex than a custom shell script if it's not packaged in the official Debian repos due to the likelihood of future dependency and maintenance issues.
