### ISSUE TITLE
Enable 32bit repositories by default to make installing and using Steam application more user friendly

### ISSUE THREAD

**Issue by Scyt4le** [SpiralLinux/SpiralLinux-project#42]
Hello,

This is a suggestion to make Spiral Linux more user friendly for people who want to use their PC for gaming via the very popular Steam application.

Debian hides the steam package as 32bit package repositories are not enabled by default and it's not possible to know and to solve this issue without searching for a solution in the Debian wiki. This will turn away beginners from Spiral Linux (and/or Debian) as in upstream distributions like Ubuntu there is no further action needed by the user to install steam an play games.

This is the source for the solution:

[The Debian Wiki:](https://wiki.debian.org/Steam)

Enable 32 bit:
`dpkg --add-architecture i386`

Additionally installing Steam does not pull in all needed dependencies; a lot of 32bit games refuses to start unless you install these packages manually. Maybe include them or declare them as dependencies as this is again an issue which you cannot solve on your own without consulting the Debian wiki:

`apt install mesa-vulkan-drivers libglx-mesa0:i386 mesa-vulkan-drivers:i386 libgl1-mesa-dri:i386`

This is not a big thing but it surely turned my away from Debian the first time I tried it. So hopefully this suggestion is useful.

Kind regards,

Scyt4le

**Comment by geckolinux** [comment]
Hi there, thanks a lot for the suggestion. I admit I know nothing about the intricacies of Steam or the gaming side of Linux in general. But I don't think that preinstalling those libraries would be ideal for SpiralLinux. The ` dpkg --add-architecture i386` command isn't necessary, the 32-bit libraries are installable out of the box according to my testing. However I think it's best to leave that to users that need them, because it would add around 50MB to the ISO size and 200MB of disk space. Plus I suspect that most users are going to install the Flatpak version of Steam, which brings along its own libraries/runtime, making the pre-installed ones redundant.
