### ISSUE TITLE
KDE desktop installation fails while installaing from synaptic package manager or tasksel

### ISSUE THREAD

**Issue by samarkv** [SpiralLinux/SpiralLinux-project#62]
KDE desktop installation fails while installing from synaptic package manager or tasksel. It is due to unresolved dependency caused by library packages installed from backports repository while the installer expects those packages from stable repository. I am giving a link to two videos from my channel where you will know exactly which unresolved dependency are causing failure of KDE desktop installation.

Video links -
1) https://youtu.be/IjtQj9oPXiU
2) https://youtu.be/C6GxmpItXR0

**Comment by geckolinux** [comment]
Hi there, thanks for the report and thanks for the Youtube coverage.

In general I can't offer support for the Builder edition since it's basically a blank slate and the possibilities and methods of customizing it are practically infinite. However, what you were trying to do will definitely work.

Regarding tasksel, the desired component for installation needs to be selected first with the **spacebar** before proceeding.

Regarding the Synaptic troubles, It can't be a matter of missing dependencies or problems with Backports, since the SpiralLinux Plasma ISO can be successfully generated using the exact same packages and Debian repository configuration. I think that maybe you just needed to refresh the package indexes.

In general, when you see broken packages, the solution is usually via refreshing the package indexes and/or **removing** conflicting packages, not installing additional ones. Broken packages will never be resolved by installing more packages, because if a resolution was possible via any other package in the available repositories then APT would install it automatically to satisfy the dependencies.

In my test it allowed me to proceed with the same selections you tried:

_**All the packages selected in the KDE Desktop section (except one `gambas*` package that was broken and was deselected):**_

![Screenshot from 2022-07-30 08-51-48](https://user-images.githubusercontent.com/2692138/181918208-00290ee1-8f50-447b-a5d1-f666ad76309e.png)

_**`kde-full` full KDE installation metapackage:**_

![Screenshot from 2022-07-30 08-54-55](https://user-images.githubusercontent.com/2692138/181918262-b04c80e6-21e4-4d15-ae4f-e79115c8e7ce.png)

_**`kde-standard` metapackage:**_

![Screenshot from 2022-07-30 08-55-34](https://user-images.githubusercontent.com/2692138/181918280-529b820d-29b6-410b-b406-1a02eb332400.png)

**Comment by samarkv** [comment]
I have again made a video for KDE install using tasksel. I selected the KDE option using spacebar. But installation is failing due to unresolved package dependency.

Please watch my detailed video on this subject which will be released at 1am IST tomorrow.

**Comment by samarkv** [comment]
If you watch my both videos I always do apt update before installing new desktop. So package indexes are refreshed before installation.

**Comment by geckolinux** [comment]
It could always be a network error or a local Debian mirror that is out of sync. This is my attempt with `tasksel` to install KDE on a fresh installation:
![Screenshot from 2022-07-30 09-54-05](https://user-images.githubusercontent.com/2692138/181919949-839ed555-1402-476c-8768-d7c25cfb782b.png)

**Comment by samarkv** [comment]
check this out 
![Screenshot_20220729_155812](https://user-images.githubusercontent.com/107233376/181919691-c4b74478-c261-4bf7-b10e-d23f105a0294.png)

**Comment by samarkv** [comment]
I changed the mirrors from main to India and back to main. But both installation attempts failed.

**Comment by samarkv** [comment]
I will give another try in next few days.

**Comment by geckolinux** [comment]
It appears that `gdb` and `gdb-minimal` conflict with each other. Please try installing just one of them.

**Comment by samarkv** [comment]
I finally found out the issue. It is with india server.
![Screenshot_20220801_142423](https://user-images.githubusercontent.com/107233376/182118509-5be49d51-5021-4081-892c-a7d98708c5ab.png)
.

**Comment by samarkv** [comment]
APT does not install one of the two packages gdb or gdb-minimal as full packaging indexes are yet to downloaded and refreshed. This is because of repository download issue with India server shown in screenshot above.

**Comment by samarkv** [comment]
If I use main server, then I am able to install KDE desktop using any expert install method.
