### ISSUE TITLE
Installation fails for VM

### ISSUE THREAD

**Issue by samarkv** [SpiralLinux/SpiralLinux-project#7]
Installation of Spirallinux VM fails when manual partitioning is choosen.

Steps to create the problem-
1) Create a Spirallinux  VM with debian 10 template in gnome boxes. Assign 4gb ram and 25gb vdd.
2) Start the installation process. 
3) At disk partitioning stage, choose manual partitioning method.
4) Create either MBR or GPT style partitions.
5) Create 300mb boot partition, 4gb swap partition and approx 19.27gb of root partition. Confirm the partitions.
6) Installer will complete the partitioning and start copying files to system.
7) After file copying is done, installer will remove the 7 live packages.
8) Right after the removal of 7 live packages and before the creation of initramfs starts,  the installer will show "installation failed with error code 100".

Installation failed 6/6 times when manual partitioning is chosen to install a VM. Not yet tried on bare metal.

If we select erase disk option while installing VM, installation is successful.

**Comment by geckolinux** [comment]
Thanks for the report.
What filesystem was selected for the root partition?
Was the VM emulating a legacy BIOS or an EFI system?

**Comment by samarkv** [comment]
I have tried EFI system with both MBR and GPT type manual partitioning along with btrfs filesystem for root partition. All the 6 installation efforts failed.

**Comment by samarkv** [comment]
I have tried EFI system with both MBR and GPT type manual partitioning along with btrfs filesystem for root partition. All the 6 installation efforts failed.

**Comment by geckolinux** [comment]
Thanks again for reporting. It looks like there were two different issues here:

- If the boot partition is manually mounted to `/boot` it needs to be somewhere around 600mb in size at minimum, so the "error code 100" was due to user misconfiguration.
- But thank you for reporting your experience, because it brought to light an unrelated issue where the GRUB bootloader installation step was failing due to a quirk in the Calamares manual partitioning mode. A fix has been included in the latest release: https://github.com/SpiralLinux/SpiralLinux-project/releases/tag/11.220610
